// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPVno1BtwowXAzlFAQIF3A0PIHVWyqBKY',
    appId: '1:339655468621:android:f6041e015d385fe0789e04',
    messagingSenderId: '339655468621',
    projectId: 'workshoporangeproject',
    storageBucket: 'workshoporangeproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoYzVGagQGR3rfl16S9xPO4XG0qufo8v0',
    appId: '1:339655468621:ios:e24f9ebebce83376789e04',
    messagingSenderId: '339655468621',
    projectId: 'workshoporangeproject',
    storageBucket: 'workshoporangeproject.appspot.com',
    iosClientId: '339655468621-fqqvlpfvdt6h3marfou5ppdp9obppjl3.apps.googleusercontent.com',
    iosBundleId: 'com.example.workshopProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoYzVGagQGR3rfl16S9xPO4XG0qufo8v0',
    appId: '1:339655468621:ios:6f15adc299b6db03789e04',
    messagingSenderId: '339655468621',
    projectId: 'workshoporangeproject',
    storageBucket: 'workshoporangeproject.appspot.com',
    iosClientId: '339655468621-bclftst9ikm8hakqfegsn64kr7itcv90.apps.googleusercontent.com',
    iosBundleId: 'y',
  );
}
